### ISSUE TITLE
tsx/jsx comments

### ISSUE THREAD

**Issue by haydenrou** [haydenrou/dotfiles#7]
- Add setup for tsx/jsx commenting
    - [nvim-ts-context-commentstring](https://github.com/JoosepAlviste/nvim-ts-context-commentstring) may do the trick

**Comment by haydenrou** [comment]
https://github.com/jonnyjones99/dotfiles/blob/main/.config/nvim/lua/plugins-setup.lua#L196

**Comment by haydenrou** [comment]
https://github.com/tjdevries/config_manager/blob/master/xdg_config%2Fnvim%2Flua%2Ftj%2Fsnips%2Fft%2Fgo.lua

**Comment by jonnyjones99** [comment]
_Hey!_

You can fix that issue with this plugin: [Plugin](https://github.com/JoosepAlviste/nvim-ts-context-commentstring](https://github.com/JoosepAlviste/nvim-ts-context-commentstring).

I'm using it in conjuction with 

Here's a little snippet of how I'm using it in my setup:

## Lazy plugin:
`	{
		"nvim-treesitter/nvim-treesitter",
		build = ":TSUpdate",
		event = "VeryLazy",

		dependencies = {
			"JoosepAlviste/nvim-ts-context-commentstring",
		},

		config = function()
			require("plugins.treesitter")
		end,
	},
`

## Config:
`
local commentstringOK, ts_context_commentstring = pcall(require, "ts_context_commentstring")
if not commentstringOK then
	vim.notify("ts_context_commentstring could not be loaded")
	return
end

require("ts_context_commentstring").setup({})
`

Hope that helps! 👍💯

**Comment by haydenrou** [comment]
This is great, thanks a lot! I added the plugin as suggested, but omitted the specific config as I don't use `vim-notify`. I also had to add [the comment.nvim specific pre-hook for the new plugin](https://github.com/JoosepAlviste/nvim-ts-context-commentstring/wiki/Integrations#commentnvim). But now it works like a charm!

You can see the attached PR for a full list of the changes. Thanks for the suggestion :)
